# Data parameters
data:
    dataset: mnist
    data_dir: data/mnist-data
    input_size: [28,28]
    input_channels: 1
    num_classes: 10
    valid_size: 0.1

# Training parameters
training:
    output_folder: ./output_conf
    task: classification
    learner: selfconfid
    nb_epochs: 10
    batch_size: 128
    loss:
        name: selfconfid_mse
        weighting: 1
    optimizer:
        name: sgd
        lr: 0.001
        momentum: 0.9
        weight_decay: 0.0001
    lr_schedule:
    smoother: 0.1
    metrics: ['accuracy', 'auc', 'ap_success', 'ap_errors']
    pin_memory: False
    num_workers: 2
    augmentations:
        normalize: [[0.1307,], [0.3081,]]


# Model parameters
model:
    name: mlp_selfconfid
    resume: /home/william/511/git/project_511/ConfidNet/confidnet/output/model_epoch_010.ckpt
    hidden_size: 1000
    is_dropout: True



